language: php
php:
  - 5.3
  - 5.4
#  - 5.5
#  - 5.6
#  - hhvm

# optionally specify a list of environments, for example to test different RDBMS
env:
- DB=mysql
- DB=pgsql
#- DB=mariadb

# maybe move this to the tests or bootstrap too..
before_script:
- if [[ "$DB" == "pgsql" ]]; then psql -c "DROP DATABASE IF EXISTS adodb_test;" -U postgres; fi
- if [[ "$DB" == "pgsql" ]]; then psql -c "CREATE DATABASE adodb_test;" -U postgres; fi
- if [[ "$DB" == "mysql" ]]; then mysql -e "CREATE DATABASE IF NOT EXISTS adodb_test;" -uroot; fi

script: phpunit --configuration tests/phpunit/phpunit_$DB.xml --coverage-text
