<?php
/**
 * ADOdb Library main include file.
 *
 * This file is part of ADOdb, a Database Abstraction Layer library for PHP.
 *
 * @package ADOdb
 * @link https://adodb.org Project's web site and documentation
 * @link https://github.com/ADOdb/ADOdb Source code and issue tracker
 *
 * The ADOdb Library is dual-licensed, released under both the BSD 3-Clause
 * and the GNU Lesser General Public Licence (LGPL) v2.1 or, at your option,
 * any later version. This means you can use it in proprietary products.
 * See the LICENSE.md file distributed with this source code for details.
 * @license BSD-3-Clause
 * @license LGPL-2.1-or-later
 *
 * @copyright 2000-2013 John Lim
 * @copyright 2014 Damien Regad, Mark Newnham and the ADOdb community
 */

use ADOdb\Resources\MySQL\ADOConnection as ADOConnection;


require 'vendor/autoload.php';
$loader = new Riimu\Kit\ClassLoader\ClassLoader();

$loader->addBasePath(__DIR__ . '/../');
$loader->addPrefixPath([
'CustomDriver\Resources\MyTest',
'CustomDriver\Resources',
'ADOdb\Resources\MySQL',
'ADOdb\Resources\SQLite',
'ADOdb\Resources\SqlServer',
'ADOdb\Resources\Oracle',
'ADOdb\Resources\IBMDB2',
'ADOdb\Resources',
]);
$loader->register();

// The ADOdb extension is no longer maintained and effectively unsupported
// since v5.04. The library will not function properly if it is present.
if(defined('ADODB_EXTENSION')) {
	$msg = "Unsupported ADOdb Extension (v" . ADODB_EXTENSION . ") detected! "
		. "Disable it to use ADOdb";

	$errorfn = defined('ADODB_ERROR_HANDLER') ? ADODB_ERROR_HANDLER : false;
	if ($errorfn) {
		$conn = false;
		$errorfn('ADOdb', basename(__FILE__), -9999, $msg, null, null, $conn);
	} else {
		die($msg . PHP_EOL);
	}
}

//==============================================================================================
// CONSTANT DEFINITIONS
//==============================================================================================


if (!defined('ADODB_SETUP')) {
	define('ADODB_SETUP',1);

/**
 * Set ADODB_DIR to the directory where this file resides...
 * This constant was formerly called $ADODB_RootPath
 */
if (!defined('ADODB_DIR')) {
	define('ADODB_DIR',dirname(__FILE__));
}

//==============================================================================================
// GLOBAL VARIABLES
//==============================================================================================

GLOBAL
	$ADODB_vers,		// database version
	$ADODB_COUNTRECS,	// count number of records returned - slows down query
	$ADODB_CACHE_DIR,	// directory to cache recordsets
	$ADODB_CACHE,
	$ADODB_CACHE_CLASS,
	$ADODB_COMPAT_FETCH, // If $ADODB_COUNTRECS and this is true, $rs->fields is available on EOF
	$ADODB_FETCH_MODE,	// DEFAULT, NUM, ASSOC or BOTH. Default follows native driver default...
	$ADODB_GETONE_EOF,
	$ADODB_QUOTE_FIELDNAMES; // Allows you to force quotes (backticks) around field names in queries generated by getinsertsql and getupdatesql.

//==============================================================================================
// GLOBAL SETUP
//==============================================================================================

/*********************************************************
 * Controls $ADODB_FORCE_TYPE mode. Default is ADODB_FORCE_VALUE (3).
 * Used in GetUpdateSql and GetInsertSql functions. Thx to Niko, nuko#mbnet.fi
 * @link https://adodb.org/dokuwiki/doku.php?id=v5:reference:adodb_force_type
 *
 * 0 = ignore empty fields. All empty fields in array are ignored.
 * 1 = force null. All empty, php null and string 'null' fields are
 *     changed to sql NULL values.
 * 2 = force empty. All empty, php null and string 'null' fields are
 *     changed to sql empty '' or 0 values.
 * 3 = force value. Value is left as it is. Php null and string 'null'
 *     are set to sql NULL values and empty fields '' are set to empty '' sql values.
 * 4 = force value. Like 1 but numeric empty fields are set to zero.
 */
define('ADODB_FORCE_IGNORE',0);
define('ADODB_FORCE_NULL',1);
define('ADODB_FORCE_EMPTY',2);
define('ADODB_FORCE_VALUE',3);
define('ADODB_FORCE_NULL_AND_ZERO',4);
// ********************************************************


/**
 * Constants for returned values from the charMax and textMax methods.
 * If not specifically defined in the driver, methods return the NOTSET value.
 */
define ('ADODB_STRINGMAX_NOTSET', -1);
define ('ADODB_STRINGMAX_NOLIMIT',-2);

/*
	* Defines the the default meta type returned
	* when ADOdb encounters a type that it is not
	* defined in the metaTypes.
	*/
if (!defined('ADODB_DEFAULT_METATYPE'))
	define ('ADODB_DEFAULT_METATYPE','N');

define('ADODB_BAD_RS','<p>Bad $rs in %s. Connection or SQL invalid. Try using $connection->debug=true;</p>');

// allow [ ] @ ` " and . in table names
define('ADODB_TABLE_REGEX','([]0-9a-z_\:\"\`\.\@\[-]*)');

// prefetching used by oracle
if (!defined('ADODB_PREFETCH_ROWS')) {
	define('ADODB_PREFETCH_ROWS',10);
}


/**
 * Fetch mode
 *
 * Set global variable $ADODB_FETCH_MODE to one of these constants or use
 * the SetFetchMode() method to control how recordset fields are returned
 * when fetching data.
 *
 *   - NUM:     array()
 *   - ASSOC:   array('id' => 456, 'name' => 'john')
 *   - BOTH:    array(0 => 456, 'id' => 456, 1 => 'john', 'name' => 'john')
 *   - DEFAULT: driver-dependent
 */
define('ADODB_FETCH_DEFAULT', 0);
define('ADODB_FETCH_NUM', 1);
define('ADODB_FETCH_ASSOC', 2);
define('ADODB_FETCH_BOTH', 3);

/**
 * Associative array case constants
 *
 * By defining the ADODB_ASSOC_CASE constant to one of these values, it is
 * possible to control the case of field names (associative array's keys)
 * when operating in ADODB_FETCH_ASSOC fetch mode.
 *   - LOWER:  $rs->fields['orderid']
 *   - UPPER:  $rs->fields['ORDERID']
 *   - NATIVE: $rs->fields['OrderID'] (or whatever the RDBMS will return)
 *
 * The default is to use native case-names.
 *
 * The values of these constants match PHP's CASE_LOWER and CASE_UPPER.
 *
 * NOTE: This functionality is not implemented everywhere, it currently
 * works only with: mssql, odbc, oci8 and ibase derived drivers.
 */
define('ADODB_ASSOC_CASE_LOWER', 0);
define('ADODB_ASSOC_CASE_UPPER', 1);
define('ADODB_ASSOC_CASE_NATIVE', 2);


if (!defined('TIMESTAMP_FIRST_YEAR')) {
	define('TIMESTAMP_FIRST_YEAR',100);
}

/**
 * AutoExecute constants
 * (moved from adodb-pear.inc.php since they are only used in here)
 */
define('DB_AUTOQUERY_INSERT', 1);
define('DB_AUTOQUERY_UPDATE', 2);


function ADODB_Setup() {
	GLOBAL
	$ADODB_vers,		// database version
	$ADODB_COUNTRECS,	// count number of records returned - slows down query
	$ADODB_CACHE_DIR,	// directory to cache recordsets
	$ADODB_FETCH_MODE,
	$ADODB_CACHE,
	$ADODB_CACHE_CLASS,
	$ADODB_FORCE_TYPE,
	$ADODB_GETONE_EOF,
	$ADODB_QUOTE_FIELDNAMES;

	if (empty($ADODB_CACHE_CLASS)) {
		$ADODB_CACHE_CLASS =  '\ADOdb\Resources\ADODBCacheFile' ;
	}
	$ADODB_FETCH_MODE = ADODB_FETCH_DEFAULT;
	$ADODB_FORCE_TYPE = ADODB_FORCE_VALUE;
	$ADODB_GETONE_EOF = null;

	if (!isset($ADODB_CACHE_DIR)) {
		$ADODB_CACHE_DIR = '/tmp'; //(isset($_ENV['TMP'])) ? $_ENV['TMP'] : '/tmp';
	} else {
		// do not accept url based paths, eg. http:/ or ftp:/
		if (strpos($ADODB_CACHE_DIR,'://') !== false) {
			die("Illegal path http:// or ftp://");
		}
	}

	/**
	 * ADODB version as a string.
	 */
	$ADODB_vers = 'v5.23.0-dev  Unreleased';

	/**
	 * Determines whether recordset->RecordCount() is used.
	 * Set to false for highest performance -- RecordCount() will always return -1 then
	 * for databases that provide "virtual" recordcounts...
	 */
	if (!isset($ADODB_COUNTRECS)) {
		$ADODB_COUNTRECS = true;
	}
}


//==============================================================================================
// CHANGE NOTHING BELOW UNLESS YOU ARE DESIGNING ADODB
//==============================================================================================
ADODB_Setup();

/**
 * For transaction handling.
 *
 * @param $dbms
 * @param $fn
 * @param $errno
 * @param $errmsg
 * @param $p1
 * @param $p2
 * @param $thisConnection
 */
function ADODB_TransMonitor($dbms, $fn, $errno, $errmsg, $p1, $p2, &$thisConnection) {
	//print "Errorno ($fn errno=$errno m=$errmsg) ";
	$thisConnection->_transOK = false;
	if ($thisConnection->_oldRaiseFn) {
		$errfn = $thisConnection->_oldRaiseFn;
		$errfn($dbms, $fn, $errno, $errmsg, $p1, $p2,$thisConnection);
	}
}

//==============================================================================================
// HELPER FUNCTIONS
//==============================================================================================

/**
 * Instantiate a new Connection class for a specific database driver.
 *
 * @param string $db Database Connection object to create. If undefined,
 *	use the last database driver that was loaded by ADOLoadCode().
	*
	* @return ADOConnection|false The freshly created instance of the Connection class
	*                             or false in case of error.
	*/
function ADONewConnection(?string $db=null,?string $customPath=null) {

	 
	$driverData = [
		'mysqli' => 'MySQL',
		'oci8'   => 'Oracle',
		'db2'    => 'IBMDB2',
		'sqlite3' => 'SQLite',
		'mssqlnative' => 'SqlServer'
	];

	if (!array_key_exists($db, $driverData)) {
		die('Invalid Driver Name');
	}
	
	if ($customPath) {
		$classPath = $customPath;
		$driverPath = ltrim(str_replace('\\', '/',$classPath) . '.php','\\');
		$includePath = stream_resolve_include_path($driverPath);
	} else {
		$driverPath  = sprintf('ADOdb/Resources/%s/ADOConnection.php', $driverData[$db]);
		$includePath = stream_resolve_include_path($driverPath);
		$classPath   = sprintf('\ADOdb\Resources\%s\ADOConnection', $driverData[$db]);
	}

	require_once $includePath;
	
	$object = new $classPath($db);

	return $object;

}

function newADOConnection(?string $db=null,?string $customClass=null) {
	return ADONewConnection($db, $customClass);
}



/**
 * Get a new Data Dictionary object for the connection.
 *
 * @param ADOConnection $conn
 * @param string        $drivername
 *
 * @return ADODB_DataDict|false
 */
function newDataDictionary(&$conn, $drivername='') {
	
	$dataDictClassFile = sprintf(
		'%s/Resources/%s/DataDictionary.php',
		ADODB_DIR,
		$conn->getDataDictionaryProvider()
	);

	$dataDictClass = sprintf(
		'ADOdb\Resources\%s\DataDictionary',
		$conn->getDataDictionaryProvider()
	);

	require_once $dataDictClassFile;
	$conn->dictionaryObject = new $dataDictClass($conn);

	return $conn->dictionaryObject;

}
}
